name: CI CD

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:

  test-and-build:

    runs-on: ubuntu-latest

    steps:

      - name: Get the code
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install pytest
        run: pip install pytest

      - name: Run tests
        run: pytest

      - name: Build website
        run: |
          mkdir build
          cp index.html build/

      - name: Upload website
        uses: actions/upload-pages-artifact@v3
        with:
          path: build

  deploy:

    needs: test-and-build

    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4